name: Build

on:
  push:
    branches-ignore:
      - 'renovate/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v7
        name: Checkout sources

      - uses: actions/setup-java@v5
        name: Set up JDK 17
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: gradle/actions/setup-gradle@v6
        name: Setup Gradle

      - name: Build Artifact
        run: "chmod +x ./gradlew && ./gradlew build"

      - uses: actions/upload-artifact@v7
        name: Save Artifact
        with:
          name: "PlayerTracer-b${{ github.run_number }}"
          path: build/libs/*.jar